# test-pipeline.yaml
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: test-pipeline
spec:
  resources: # 为 Tasks 提供输入和输出资源声明
    - name: git-res
      type: git
    - name: harbor-image
      type: image
  tasks: # 添加task到流水线中
    # 运行应用测试
    - name: test
      taskRef: # 关联的 Task 资源对象
        name: test
      resources: # 关联的 PipelineResource
        inputs: 
          - name: repo # Task 输入名称
            resource: git-res # Pipeline 资源名称
    # 构建并推送 Docker 镜像
    - name: build-and-push
      taskRef:
        name: build-and-push
      runAfter: # 在 test 名称之后运行 build-and-push
        - test # 测试任务执行之后
      resources: # 关联的 PipelineResource
        inputs: 
          - name: repo # 指定输入的git仓库资源
            resource: git-res
        outputs: # 指定输出的镜像资源 
          - name: builtImage
            resource: harbor-image