{{- if .Values.tags.mysql }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "zadig.mysql.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "zadig.mysql.labels" . | nindent 4 }}
{{- if .Values.additionalLabels }}
{{ toYaml .Values.additionalLabels | trimSuffix "\n" | indent 4 }}
{{- end }}
{{- if .Values.additionalAnnotations }}
  annotations:
{{ toYaml .Values.additionalAnnotations | trimSuffix "\n" | indent 4 }}
{{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "zadig.mysql.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "zadig.mysql.name" . }}
  template:
    metadata:
      labels:
        {{- include "zadig.mysql.selectorLabels" . | nindent 8 }}
{{- if .Values.podLabels }}
{{ toYaml .Values.podLabels | indent 8 }}
{{- end }}
{{- if .Values.podAnnotations }}
      annotations:
{{ toYaml .Values.podAnnotations | trimSuffix "\n" | indent 8 }}
{{- end }}
    spec:
{{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
{{- end }}
      containers:
        - name: mysql
          image: {{ .Values.global.image.registry }}/{{ .Values.mysql.image.repository }}:{{ .Values.mysql.image.tag}}
          imagePullPolicy: {{ .Values.global.image.pullPolicy | default "Always" }}
          env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: password
          ports:
          - containerPort: 3306
            name: mysql
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
      {{ if and .Values.mysql.persistence.enabled .Values.mysql.persistence.existingClaim }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ tpl .Values.mysql.persistence.existingClaim . }}
      {{- else if not .Values.mysql.persistence.enabled }}
      volumes:
        - name: data
          emptyDir: {}
      {{- else if and .Values.mysql.persistence.enabled (not .Values.mysql.persistence.existingClaim) }}
  volumeClaimTemplates:
    - metadata:
        name: data
        labels:
          {{ include "zadig.mysql.selectorLabels" . | nindent 10 }}
      spec:
        {{ if .Values.mysql.storageClass }}
        storageClassName: {{ .Values.mysql.storageClass }}
        {{- end }}
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.mysql.persistence.size | quote }}
      {{- end }}
{{- end }}