apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-post-upgrade"
  labels:
    {{- include "zadig.postHook.labels" . | nindent 4 }}
{{- if .Values.additionalLabels }}
{{ toYaml .Values.additionalLabels | trimSuffix "\n" | indent 4 }}
{{- end }}
  annotations:
    "helm.sh/hook": post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    "helm.sh/hook-weight": "-1"
{{- if .Values.additionalAnnotations }}
{{ toYaml .Values.additionalAnnotations | trimSuffix "\n" | indent 4 }}
{{- end }}
spec:
  template:
    metadata:
      labels:
        {{- include "zadig.postHook.selectorLabels" . | nindent 8 }}
{{- if .Values.podLabels }}
{{ toYaml .Values.podLabels | indent 8 }}
{{- end }}
{{- if .Values.podAnnotations }}
      annotations:
{{ toYaml .Values.podAnnotations | trimSuffix "\n" | indent 8 }}
{{- end }}
    spec:
      restartPolicy: Never
      containers:
        - name: post-upgrade-job
          image: {{ .Values.global.image.registry }}/{{ .Values.ua.image.repository }}:{{ .Values.ua.image.tag }}
          imagePullPolicy: {{ .Values.global.image.pullPolicy | default "Always" }}
          resources:
            limits:
              cpu: {{ .Values.ua.resources.limits.cpu }}
              memory: {{ .Values.ua.resources.limits.memory }}
            requests:
              cpu: {{ .Values.ua.resources.requests.cpu }}
              memory: {{ .Values.ua.resources.requests.memory }}
          volumeMounts:
            - mountPath: /etc/encryption
              name: aes-key
              readOnly: true
          args:
            - "migrate"
            - "-c"
            - {{ .Values.connections.mongodb.connectionString | quote }}
            - "-d"
            - {{ default "zadig" .Values.connections.mongodb.db | quote }}
            - "-f"
            - "$(FROM_VERSION)"
            - "-t"
            - {{ .Chart.Version | quote }}
          env:
            - name: FROM_VERSION
              valueFrom:
                configMapKeyRef:
                  name: "{{ .Release.Name }}-post-install"
                  key: VERSION
                  optional: true
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: zadig-aes-key
                  key: aesKey
            - name: ADDRESS
              value: {{ default "http" .Values.protocol }}://{{- include "zadig.endpoint" . }}
            - name: MYSQL_USER
              value: {{ .Values.connections.mysql.auth.user }}
            - name: MYSQL_PASSWORD
              value: {{ .Values.connections.mysql.auth.password | quote }}
            - name: MYSQL_HOST
              value: {{ .Values.connections.mysql.host }}
            - name: MYSQL_USER_DB
              value: {{ .Values.connections.mysql.db.user }}
            - name: REDIS_HOST
              value: {{ .Values.connections.redis.host }}
            - name: REDIS_PORT
              value: {{ .Values.connections.redis.port | quote }}
            - name: REDIS_USERNAME
              value: {{ .Values.connections.redis.user | quote }}
            - name: REDIS_PASSWORD
              value: {{ .Values.connections.redis.password | quote }}
            - name: REDIS_COMMON_CACHE_DB
              value: {{ .Values.connections.redis.db.cache | quote }}
{{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
{{- end }}
      volumes:
        - name: aes-key
          secret:
            secretName: zadig-aes-key
            items:
              - key: aesKey
                path: aes
