# Throttle-NodeQOS.yaml
apiVersion: ensurance.crane.io/v1alpha1
kind: NodeQOS
metadata:
  name: 'watermark2'
  labels:
    app: 'system'
spec:
  nodeQualityProbe:
    timeoutSeconds: 10
    nodeLocalGet:
      localCacheTTLSeconds: 60
  rules:
    - name: 'cpu-usage'
      avoidanceThreshold: 2
      restoredThreshold: 2
      actionName: 'throttle'
      strategy: 'None'
      metricRule:
        name: 'cpu_total_usage'
        value: 6000