apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: sample-topic
spec:
  type: bindings.kafka
  version: v1
  metadata:
    - name: brokers
      value: localhost:9092
    - name: topics
      value: sample
    - name: consumerGroup
      value: group1
    - name: publishTopic
      value: sample
    - name: authRequired
      value: "false"
