# selfsigned-issuer.yaml
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
  namespace: default
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: private-ca
  namespace: default
spec:
  isCA: true
  commonName: private-ca
  subject:
    organizations:
      - example.com
    organizationalUnits:
      - DevOps
  secretName: private-ca-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: private-ca-issuer
  namespace: default
spec:
  ca:
    secretName: private-ca-secret