{{- if .Values.tags.mongodb }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "zadig.mongodb.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "zadig.mongodb.labels" . | nindent 4 }}
{{- if .Values.additionalLabels }}
{{ toYaml .Values.additionalLabels | trimSuffix "\n" | indent 4 }}
{{- end }}
{{- if .Values.additionalAnnotations }}
  annotations:
{{ toYaml .Values.additionalAnnotations | trimSuffix "\n" | indent 4 }}
{{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "zadig.mongodb.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "zadig.mongodb.name" . }}
  template:
    metadata:
      labels:
        {{- include "zadig.mongodb.selectorLabels" . | nindent 8 }}
{{- if .Values.podLabels }}
{{ toYaml .Values.podLabels | indent 8 }}
{{- end }}
{{- if .Values.podAnnotations }}
      annotations:
{{ toYaml .Values.podAnnotations | trimSuffix "\n" | indent 8 }}
{{- end }}
    spec:
{{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
{{- end }}
      containers:
        - name: mongodb
          image: {{ .Values.global.image.registry }}/{{ .Values.mongodb.image.repository }}:{{ .Values.mongodb.image.tag}}
          imagePullPolicy: {{ .Values.global.image.pullPolicy | default "Always" }}
          args: ["--dbpath","/data/db"]
          env:
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongodb-secret
                key: password
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongodb-secret
                key: username
          ports:
          - containerPort: 27017
            name: mongodb
          volumeMounts:
            - name: data
              mountPath: /data/db
    {{ if and .Values.mongodb.persistence.enabled .Values.mongodb.persistence.existingClaim }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ tpl .Values.mongodb.persistence.existingClaim . }}
    {{- else if not .Values.mongodb.persistence.enabled }}
      volumes:
        - name: data
          emptyDir: {}
    {{- else if and .Values.mongodb.persistence.enabled (not .Values.mongodb.persistence.existingClaim) }}
  volumeClaimTemplates:
    - metadata:
        name: data
        labels:
          {{ include "zadig.mongodb.selectorLabels" . | nindent 10 }}
      spec:
        {{ if .Values.mongodb.storageClass }}
        storageClassName: {{ .Values.mongodb.storageClass }}
        {{- end }}
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.mongodb.persistence.size | quote }}
    {{- end }}
{{- end }}