# api-loadbalancer-service.yaml
apiVersion: v1  
kind: Service  
metadata:  
  name: api-loadbalancer  
spec:  
  type: LoadBalancer  
  selector:  
    app: api-server  
  ports:  
    - protocol: TCP  
      port: 443  
      targetPort: 8443  