# web-nodeport-service.yaml
apiVersion: v1  
kind: Service  
metadata:  
  name: web-nodeport
spec:  
  type: NodePort  
  selector:  
    app: nginx  
  ports:  
    - port: 80         # Service端口  
      targetPort: 80   # Pod端口  
      nodePort: 31000  # 手动指定NodePort（可选）   