# docker-dind.yaml
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   labels:
#     app: docker-dind
#   name: docker-dind-data
#   namespace: kube-ops
# spec:
#   accessModes:
#     - ReadWriteOnce
#   storageClassName: nfs-csi # local-path # 指定一个可用的 storageclass
#   resources:
#     requests:
#       storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-dind
  namespace: kube-ops
  labels:
    app: docker-dind
spec:
  selector:
    matchLabels:
      app: docker-dind
  template:
    metadata:
      labels:
        app: docker-dind
    spec:
      containers:
        - image: docker:dind
          name: docker-dind
          args:
            - --registry-mirror=https://6ivwq0yf.mirror.aliyuncs.com/ # 指定多个镜像加速器
            - --registry-mirror=https://docker.m.daocloud.io/
            - --registry-mirror=https://hub-mirror.c.163.com/
            - --registry-mirror=https://docker.mirrors.ustc.edu.cn/
            - --insecure-registry=harbor.k8s.local
          env:
            - name: DOCKER_DRIVER
              value: overlay2
            - name: DOCKER_HOST
              value: tcp://0.0.0.0:2375
            - name: DOCKER_TLS_CERTDIR # 禁用 TLS（最好别禁用）
              value: ''
          volumeMounts:
            - name: docker-dind-data-vol # 持久化docker根目录
              mountPath: /var/lib/docker/
          ports:
            - name: daemon-port
              containerPort: 2375
          securityContext:
            privileged: true # 需要设置成特权模式
      volumes:
        - name: docker-dind-data-vol
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: docker-dind
  namespace: kube-ops
  labels:
    app: docker-dind
spec:
  ports:
    - port: 2375
      targetPort: 2375
  selector:
    app: docker-dind